version: "3.8"

services:

  redis:
    image: "redis"

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  authorization-server:
    build: ./authorization-server/.
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_HOST: kafka
      SERVER_PORT: 8082
      REDIS_HOST: redis

  otp-sender:
    build: ./otp-sender/.
    depends_on:
      - kafka
      - zookeeper
    environment:
      SERVER-PORT: 8081
      KAFKA_HOST: kafka
      AUTH_EMAIL: { YOUR EMAIL }
      AUTH_EMAIL_PASSWORD: { YOUR PASSWORD }

  resource-sever:
    build: ./resource-server/.
    depends_on:
      - authorization-server
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      AUTH_SERVER_HOST: authorization-server
      AUTH_SERVER_PORT: 8082




